// src/lib/Navbar.svelte
<script lang="ts">
	import { page } from '$app/state';
	import { House, Menu, Phone } from 'lucide-svelte';

	let navbarOpen = $state(false);
	let { transparent = false } = $props();

	$effect(() => {
		transparent = page.url.pathname === '/';
	});

	function toggleNavbar() {
		navbarOpen = !navbarOpen;
	}

	const navItems = [
		{
			href: '/',
			label: 'Home',
			icon: House
		},
		{
			href: '/Contact',
			label: 'Contact',
			icon: Phone
		}
	];
</script>

<nav>
	<div>
		<div>
			<a href="/">
				<img
					src={transparent ? '/img/logo_white.png' : '/img/logo.png'}
					width="100"
					height="100"
					alt="Travis Drilling Logo"
					/>
			</a>

			<button
				type="button"
				onclick={toggleNavbar}
				aria-label="Toggle navigation"
			>
				<Menu fill="currentColor" />
			</button>
		</div>

		<div
			style="{navbarOpen ? 'display: block;' : 'display: none;'}"
			id="example-navbar-warning"
		>
			<ul>
				{#each navItems as item}
					<li>
						<a
							href={item.href}
						>
							<item.icon />
							<span>{item.label}</span>
						</a>
					</li>
				{/each}
			</ul>

			<ul>
				<!-- right side navbar items -->
			</ul>
		</div>
	</div>
</nav>

// components/Navbar.tsx
import Link from 'next/link'; // Importing Link component from Next.js
import Image from 'next/image'; // Importing Image component from Next.js

// Navbar component
const Navbar: React.FC = () => {
  return (
    // Navbar container
    <div style={{ display: 'flex', alignItems: 'center', padding: '20px' }}>
      {/* Company logo */}
      <Image
        src="/logo.png"
        alt="Travis Drilling Logo"
        width={100}
        height={100}
      />
      {/* Navigation bar */}
      <nav style={{ display: 'flex', justifyContent: 'center', alignItems: 'center' }}>
        {/* Navigation items */}
        <ul style={{ listStyle: 'none', display: 'flex', color: 'black' }}>
          <NavItem href="/">Home</NavItem>
          <NavItem href="/about">About</NavItem>
          <NavItem href="/contact">Contact</NavItem>
        </ul>
      </nav>
    </div>
  );
};

// Navigation item component
interface NavItemProps {
  href: string;
  children: React.ReactNode;
}

const NavItem: React.FC<NavItemProps> = ({ href, children }) => {
  return (
    // Navigation item
    <li style={{ margin: '0 10px' }}>
      {/* Link to the specified page */}
      <Link href={href} passHref>
        {children}
      </Link>
    </li>
  );
};

export default Navbar;
