// src/lib/Footer.svelte
<script lang="ts">
	import { SiGithub } from '@icons-pack/svelte-simple-icons';
	import { Mail, MapPin } from 'lucide-svelte';
</script>

<footer class="bg-gray-900">
	<div class="container mx-auto px-6 py-12">
		<div class="grid gap-10 md:grid-cols-2 lg:grid-cols-3">
			<!-- Brand -->
			<div>
				<img src="/img/logo_white.png" alt="Travis Drilling" class="mb-4 h-14 w-auto" />
				<p class="max-w-xs text-gray-400">
					Locally owned and operated water well drilling services serving Onoway and surrounding
					areas.
				</p>
			</div>

			<!-- Contact -->
			<div>
				<h4 class="mb-4 text-sm font-bold tracking-wider text-white uppercase">Contact</h4>
				<div class="space-y-3">
					<a
						href="mailto:contact@travisdrilling.ca"
						class="flex items-center gap-3 text-gray-400 transition-colors hover:text-white"
					>
						<Mail class="h-5 w-5 text-[#00bfff]" />
						contact@travisdrilling.ca
					</a>
					<div class="flex items-center gap-3 text-gray-400">
						<MapPin class="h-5 w-5 text-[#00bfff]" />
						Onoway, Alberta, Canada
					</div>
				</div>
			</div>

			<!-- Quick Links -->
			<div>
				<h4 class="mb-4 text-sm font-bold tracking-wider text-white uppercase">Quick Links</h4>
				<div class="space-y-2">
					<a href="/" class="block text-gray-400 transition-colors hover:text-white"> Home </a>
					<a href="/Contact" class="block text-gray-400 transition-colors hover:text-white">
						Contact
					</a>
					<a href="/#services" class="block text-gray-400 transition-colors hover:text-white">
						Services
					</a>
				</div>
			</div>
		</div>

		<!-- Bottom Bar -->
		<div
			class="mt-10 flex flex-col items-center justify-between gap-4 border-t border-gray-800 pt-6 md:flex-row"
		>
			<p class="text-sm text-gray-500">
				&copy; {new Date().getFullYear()} Travis Drilling LTD. All rights reserved.
			</p>
			<a
				href="https://github.com/Logan9312/Travis-Drilling"
				target="_blank"
				class="text-gray-500 transition-colors hover:text-white"
				aria-label="GitHub Repository"
			>
				<SiGithub size={20} />
			</a>
		</div>
	</div>
</footer>

// src/components/Footer.tsx
import React from 'react'

import Link from 'next/link'




function Footer() {
  return (
    <footer className="relative bg-gray-300 pt-8 pb-6">
      <div className="container mx-auto px-4">
        <div className="flex flex-wrap">
          <div className="w-full lg:w-6/12 px-4">
            <h4 className="text-3xl font-semibold">
              Get a Quote
            </h4>
            <h5 className="text-lg mt-0 mb-2 text-gray-700">
              Email us: {" "}
              <Link href="mailto:contact@travisdrilling.ca" className="underline">contact@travisdrilling.ca</Link>
            </h5>

          </div>
          <div className="w-full lg:w-6/12 px-4">
            <div className="flex flex-wrap items-top mb-6">
              <div className="w-full lg:w-4/12 px-4 ml-auto">
                <span className="block uppercase text-gray-600 text-sm font-bold mb-2">
                  Useful Links
                </span>
                <ul className="list-unstyled">
                  <li>
                    <Link className="text-gray-700 hover:text-gray-900 font-semibold block pb-2 text-sm"
                      href="/about">About Us
                    </Link>
                  </li>
                  <li>
                    <Link className="text-gray-700 hover:text-gray-900 font-semibold block pb-2 text-sm"
                      href="/contact">Contact Us
                    </Link>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <hr className="my-6 border-gray-400" />
        <div className="flex flex-wrap items-center md:justify-between justify-center">
          <div className="w-full md:w-4/12 px-4 mx-auto text-center">
            <div className="text-sm text-gray-600 font-semibold py-1">

              Copyright © {new Date().getFullYear()}{" "} by {" "}
              <Link
                href="https://github.com/Logan9312/Travis-Drilling"
                className="text-gray-600 hover:text-gray-900"
              >
                Logan Travis
              </Link>.
            </div>
            <div className=" text-gray-600 font-semibold py-1 ">
              <Link href="https://github.com/Logan9312/Travis-Drilling" passHref target="_blank" className="hover:text-gray-900">
                <i className="flex fab fa-github fa-xl"></i>
              </Link>
            </div>
          </div>
        </div>
      </div>
    </footer>
  )
}

export default Footer
