// src/lib/Navbar.svelte
<script lang="ts">
	import { page } from '$app/state';

	let navbarOpen = $state(false);
	let { transparent = false } = $props();

	$effect(() => {
		transparent = page.url.pathname === '/';
	});

	function toggleNavbar() {
		navbarOpen = !navbarOpen;
	}
</script>

<nav
	class="{transparent
		? 'absolute top-0 z-50 w-full'
		: 'relative bg-white shadow-lg'} mb-5 flex flex-wrap items-center justify-between px-2 py-3"
>
	<div class="container mx-auto flex flex-wrap items-center justify-between px-4">
		<div class="relative flex w-full justify-between lg:static lg:block lg:w-auto lg:justify-start">
			<a href="/">
				<img
					src={transparent ? '/img/logo_white.png' : '/img/logo.png'}
					width="100"
					height="100"
					alt="Travis Drilling Logo"
					class="mr-4 inline-block whitespace-nowrap py-2 font-bold uppercase leading-relaxed"
				/>
			</a>

			<a
				class="{transparent
					? 'text-white'
					: 'text-gray-800'} title-lg mr-4 inline-block whitespace-nowrap py-2 font-bold uppercase leading-relaxed"
				href="/"
				aria-label="Home"
			></a>

			<button
				class="block cursor-pointer rounded border border-solid border-transparent bg-transparent px-3 py-1 text-xl leading-none outline-none focus:outline-none lg:hidden"
				type="button"
				onclick={toggleNavbar}
				aria-label="Toggle navigation"
			>
				<svg
					xmlns="http://www.w3.org/2000/svg"
					viewBox="0 0 24 24"
					fill="currentColor"
					class="{transparent ? 'text-white' : 'text-gray-800'} h-6 w-6"
				>
					<path
						fill-rule="evenodd"
						d="M3 6.75A.75.75 0 013.75 6h16.5a.75.75 0 010 1.5H3.75A.75.75 0 013 6.75zM3 12a.75.75 0 01.75-.75h16.5a.75.75 0 010 1.5H3.75A.75.75 0 013 12zm0 5.25a.75.75 0 01.75-.75h16.5a.75.75 0 010 1.5H3.75a.75.75 0 01-.75-.75z"
						clip-rule="evenodd"
					/>
				</svg>
			</button>
		</div>

		<div
			class="flex-grow items-center bg-white lg:flex lg:bg-transparent lg:shadow-none {navbarOpen
				? 'block rounded shadow-lg'
				: 'hidden'}"
			id="example-navbar-warning"
		>
			<ul class="mr-auto flex list-none flex-col lg:flex-row">
				<li class="flex items-center">
					<a
						class="{transparent
							? 'text-gray-800 lg:text-white lg:hover:text-gray-300'
							: 'text-gray-800 hover:text-gray-600'} flex items-center px-4 py-4 text-xs font-bold uppercase lg:py-4"
						href="/"
					>
						<i
							class="{transparent
								? 'text-gray-500 lg:text-gray-300'
								: 'text-gray-500'} fas fa-house leading-lg mr-2 text-lg"
						></i>
						Home
					</a>
				</li>

				<li class="flex items-center">
					<a
						class="{transparent
							? 'text-gray-800 lg:text-white lg:hover:text-gray-300'
							: 'text-gray-800 hover:text-gray-600'} flex items-center px-4 py-4 text-xs font-bold uppercase lg:py-2"
						href="/Contact"
					>
						<i
							class="{transparent
								? 'text-gray-500 lg:text-gray-300'
								: 'text-gray-500'} far fa-address-card leading-lg text-lg"
						></i>
						<span class="ml-2 inline-block">Contact</span>
					</a>
				</li>
			</ul>

			<ul class="flex list-none flex-col lg:ml-auto lg:flex-row">
				<!-- right side navbar items -->
			</ul>
		</div>
	</div>
</nav>

// src/components/Navbar.tsx
import React, { useState } from 'react'
import Link from 'next/link'
import Image from 'next/image'
import { Bars3Icon } from '@heroicons/react/24/solid'

interface Props {
  transparent?: boolean
}

function Navbar(props: Props) {
  const [navbarOpen, setNavbarOpen] = useState(false);
  return (
    <nav
      className={
        (props.transparent
          ? "top-0 absolute z-50 w-full" : "relative bg-white shadow-lg") +
        " flex flex-wrap items-center justify-between px-2 py-3 "
      }
    >
      <div className="container px-4 mx-auto flex flex-wrap items-center justify-between">
        <div className="w-full relative flex justify-between lg:w-auto lg:static lg:block lg:justify-start">
          <Link
            href="/">
            <Image
              src={(props.transparent ? "/img/logo_white.png" : "/img/logo.png")}
              width={100}
              height={100}
              alt="Travis Drilling Logo"
              className=" font-bold leading-relaxed inline-block mr-4 py-2 whitespace-nowrap uppercase"
            />
          </Link>

          <Link
            className={
              (props.transparent ? "text-white" : "text-gray-800") +
              " title-lg font-bold leading-relaxed inline-block mr-4 py-2 whitespace-nowrap uppercase"
            }
            href="/"
          />
          <button
            className="cursor-pointer text-xl leading-none px-3 py-1 border border-solid border-transparent rounded bg-transparent block lg:hidden outline-none focus:outline-none"
            type="button"
            onClick={() => setNavbarOpen(!navbarOpen)}
          >
            <Bars3Icon className={(props.transparent ? "text-white" : "text-gray-800") + " h-6 w-6"} />
          </button>
        </div>
        <div
          className={
            "lg:flex flex-grow items-center bg-white lg:bg-transparent lg:shadow-none" +
            (navbarOpen ? " block rounded shadow-lg" : " hidden")
          }
          id="example-navbar-warning"
        >
          <ul className="flex flex-col lg:flex-row list-none mr-auto">
            <li className="flex items-center">
              <Link
                className={
                  (props.transparent
                    ? "lg:text-white lg:hover:text-gray-300 text-gray-800"
                    : "text-gray-800 hover:text-gray-600") +
                  " px-4 py-4 lg:py-4 flex items-center text-xs uppercase font-bold"
                }
                href="/"
              >
                <i
                  className={
                    (props.transparent
                      ? "lg:text-gray-300 text-gray-500"
                      : "text-gray-500") +
                    " fas fa-house text-lg leading-lg mr-2"
                  }
                />{" "}
                Home
              </Link>
            </li>
            <li className="flex items-center">
              <Link
                className={
                  (props.transparent
                    ? "lg:text-white lg:hover:text-gray-300 text-gray-800"
                    : "text-gray-800 hover:text-gray-600") +
                  " px-4 py-4 lg:py-2 flex items-center text-xs uppercase font-bold"
                }
                href="/about"
              >
                <i
                  className={
                    (props.transparent
                      ? "lg:text-gray-300 text-gray-500"
                      : "text-gray-500") +
                    " far fa-file-alt text-lg leading-lg mr-2"
                  }
                />{" "}
                About
              </Link>
            </li>
            <li className="flex items-center">
              <Link
                className={
                  (props.transparent
                    ? "lg:text-white lg:hover:text-gray-300 text-gray-800"
                    : "text-gray-800 hover:text-gray-600") +
                  " px-4 py-4 lg:py-2 flex items-center text-xs uppercase font-bold"
                }
                href="/contact"
              >
                <i
                  className={
                    (props.transparent
                      ? "lg:text-gray-300 text-gray-500"
                      : "text-gray-500") +
                    " far fa-address-card text-lg leading-lg "
                  }
                />
                <span className="inline-block ml-2">Contact</span>
              </Link>
            </li>

            {/*<li className="flex items-center">
              <Link
                className={
                  (props.transparent
                    ? "lg:text-white lg:hover:text-gray-300 text-gray-800"
                    : "text-gray-800 hover:text-gray-600") +
                  " px-4 py-4 lg:py-2 flex items-center text-xs uppercase font-bold"
                }
                href="/resources"
              >
                <i
                  className={
                    (props.transparent
                      ? "lg:text-gray-300 text-gray-500"
                      : "text-gray-500") +
                    " far fa-folder-open text-lg leading-lg "
                  }
                />
                <span className="inline-block ml-2">Resources</span>
              </Link>
            </li>*/}
            {/*<li className="flex items-center">
              <Link
                className={
                  (props.transparent
                    ? "lg:text-white lg:hover:text-gray-300 text-gray-800"
                    : "text-gray-800 hover:text-gray-600") +
                  " px-4 py-4 lg:py-2 flex items-center text-xs uppercase font-bold"
                }
                href="/services"
              >
                <i
                  className={
                    (props.transparent
                      ? "lg:text-gray-300 text-gray-500"
                      : "text-gray-500") +
                    " fas fa-list text-lg leading-lg "
                  }
                />
                <span className="inline-block ml-2">Services</span>
              </Link>
            </li>*/}
          </ul>
          <ul className="flex flex-col lg:flex-row list-none lg:ml-auto">
            {/* right side navbar items */}
          </ul>
        </div>
      </div>
    </nav>
  )
}

export default Navbar
